feat: add `hidden`, `properties`, and `attributes` to `waitForElement`
puppeteer/replay pull request #412
Opened 2022-12-16 10:50 UTC by jrandolf

This PR adds three new properties:

 - `attributes` - This is a dictionary of strings that will match attributes of an element. This will always be a partial match.
For example, `”attributes”: {“value”: “125”}`.
 - `properties` - This is a JS record of JSON-serializable attributes that can be used to match an element’s JSON-serializable properties. This will be a sub-tree exact match. For arrays, order matters.
 - `visible` - This is a boolean value that inverts the match criteria.

2022-12-16 10:52 UTC, OrKoN commented on test/runner.test.ts
> +  describe.only('waitForElement', async () => {
forgotten .only

2022-12-16 10:53 UTC, OrKoN requested changes
Let's update the stringify extension and add the benchmark tests in the same PR.

2022-12-16 11:18 UTC, OrKoN approved these changes

2022-12-16 11:21 UTC, merged

2024-04-17 04:33 UTC, Shannonj1 reviewed
###